# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'batchrender.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(632, 879)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        Dialog.setWhatsThis("")
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 591, 841))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_select_dir = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_select_dir.setEnabled(True)
        self.btn_select_dir.setAcceptDrops(False)
        self.btn_select_dir.setObjectName("btn_select_dir")
        self.verticalLayout.addWidget(self.btn_select_dir)
        self.lbl_selected_dir = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_selected_dir.setObjectName("lbl_selected_dir")
        self.verticalLayout.addWidget(self.lbl_selected_dir)
        self.chbox_subdir = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.chbox_subdir.setChecked(True)
        self.chbox_subdir.setObjectName("chbox_subdir")
        self.verticalLayout.addWidget(self.chbox_subdir)
        self.chbox_latest_versions = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.chbox_latest_versions.setChecked(True)
        self.chbox_latest_versions.setObjectName("chbox_latest_versions")
        self.verticalLayout.addWidget(self.chbox_latest_versions)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout_3.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_3.setSpacing(10)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.chbox_fbx = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.chbox_fbx.setObjectName("chbox_fbx")
        self.gridLayout_3.addWidget(self.chbox_fbx, 0, 0, 1, 1)
        self.chbox_obj = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.chbox_obj.setObjectName("chbox_obj")
        self.gridLayout_3.addWidget(self.chbox_obj, 1, 0, 1, 1)
        self.chbox_mb = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.chbox_mb.setObjectName("chbox_mb")
        self.gridLayout_3.addWidget(self.chbox_mb, 1, 1, 1, 1)
        self.chbox_ma = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.chbox_ma.setObjectName("chbox_ma")
        self.gridLayout_3.addWidget(self.chbox_ma, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_3.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_3.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.buttonBox_2 = QtWidgets.QDialogButtonBox(self.verticalLayoutWidget)
        self.buttonBox_2.setStandardButtons(QtWidgets.QDialogButtonBox.NoButton)
        self.buttonBox_2.setCenterButtons(True)
        self.buttonBox_2.setObjectName("buttonBox_2")
        self.verticalLayout.addWidget(self.buttonBox_2)
        self.scrollArea = QtWidgets.QScrollArea(self.verticalLayoutWidget)
        self.scrollArea.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 10))
        self.scrollArea.setMaximumSize(QtCore.QSize(16777215, 160))
        self.scrollArea.setAutoFillBackground(False)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 587, 85))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem2)
        self.pushButton_3 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.comboBox = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout.addWidget(self.comboBox)
        self.comboBox_2 = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.verticalLayout.addWidget(self.comboBox_2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem3)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.verticalLayoutWidget)
        self.buttonBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.buttonBox.setAutoFillBackground(False)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Apply|QtWidgets.QDialogButtonBox.Close)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.btn_select_dir, self.chbox_subdir)
        Dialog.setTabOrder(self.chbox_subdir, self.chbox_latest_versions)
        Dialog.setTabOrder(self.chbox_latest_versions, self.chbox_fbx)
        Dialog.setTabOrder(self.chbox_fbx, self.chbox_obj)
        Dialog.setTabOrder(self.chbox_obj, self.chbox_ma)
        Dialog.setTabOrder(self.chbox_ma, self.pushButton_2)
        Dialog.setTabOrder(self.pushButton_2, self.chbox_mb)
        Dialog.setTabOrder(self.chbox_mb, self.pushButton)
        Dialog.setTabOrder(self.pushButton, self.scrollArea)
        Dialog.setTabOrder(self.scrollArea, self.pushButton_3)
        Dialog.setTabOrder(self.pushButton_3, self.comboBox)
        Dialog.setTabOrder(self.comboBox, self.comboBox_2)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Batch Render Menu"))
        self.btn_select_dir.setText(_translate("Dialog", "Select Directory"))
        self.lbl_selected_dir.setText(_translate("Dialog", "Selected Directory..."))
        self.chbox_subdir.setText(_translate("Dialog", "Include Subdirectories"))
        self.chbox_latest_versions.setText(_translate("Dialog", "Latest Versions Only"))
        self.chbox_fbx.setText(_translate("Dialog", "FBX"))
        self.chbox_obj.setText(_translate("Dialog", "OBJ"))
        self.chbox_mb.setText(_translate("Dialog", "MB"))
        self.chbox_ma.setText(_translate("Dialog", "MA"))
        self.pushButton_2.setText(_translate("Dialog", "Add Item to List"))
        self.pushButton.setText(_translate("Dialog", "Clear List"))
        self.pushButton_3.setText(_translate("Dialog", "Output Directory"))
        self.label_2.setText(_translate("Dialog", "Selected Output Directory"))
        self.comboBox.setItemText(0, _translate("Dialog", "JPG"))
        self.comboBox.setItemText(1, _translate("Dialog", "EXR"))
        self.comboBox.setItemText(2, _translate("Dialog", "PNG"))
        self.comboBox_2.setItemText(0, _translate("Dialog", "1920x1080"))
        self.comboBox_2.setItemText(1, _translate("Dialog", "New Item"))
